### ISSUE TITLE
makefile errors

### ISSUE THREAD

**Issue by sjsrey** [darribas/gds_scipy16#1]
this is on python 2.7 ubuntu mate 16.04 with the dependencies installed

`make notebooks` results in the attached error:

![screenshot at 2016-06-11 15 12 36](https://cloud.githubusercontent.com/assets/118042/15987688/fb21486a-2fe6-11e6-8ff3-e456579367cd.png)

**Comment by sjsrey** [comment]
More info. After building a python 3 environment everything is fine.

Package list for that environment is attached.
[packages.txt](https://github.com/darribas/gds_scipy16/files/310531/packages.txt)

**Comment by darribas** [comment]
@sjsrey can you try to build the `pydata` environment spelled out [here](https://github.com/darribas/envs/blob/master/pydata.sh) and `make notebooks` with that activated? That's what I'm using and have no problems.

Ideally, I think our entire book should work both on Python 2 and 3 so maybe it's also a good idea you stick with 3 and develop in 2?

**Comment by sjsrey** [comment]
Working with the `pydata` environment is great. No problems except for `folium` is missing in the installer script. But this does fix the build issue.

**Comment by darribas** [comment]
Excellent! Closing here and I'll add `folium` when I move `pydata.sh` to the project here.
