### ISSUE TITLE
Part 1: Spatial data processing: Error with 'all_polygons[0].centriod'

### ISSUE THREAD

**Issue by nickbearman** [darribas/gds_scipy16#11]
When I am working through Part 1, I am getting an error with running this line (code block 16 at https://github.com/darribas/gds_scipy16/blob/master/content/part1/01_data_processing.ipynb):
`all_polygons[0].centriod`
`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`<ipython-input-186-6380caec5f91> in <module>()`
`----> 1 all_polygons[0].centriod #doesn't work`

`AttributeError: 'Polygon' object has no attribute 'centriod'`

The rest of the functions (area, polygon, etc.) work fine. 

Extracting one polygon:
`polygon = all_polygons[0]`
works fine, so
`polygon.centriod` gives me a sensible answer. 

I have recently setup and installed as per the instructions on Ubuntu 17.10
I know when installing I had to have a later version of geopandas (as 0.2 wasn't available) and possibly mplleaflet and cartopy as well. I can't find out which versions they are, sorry!

Any suggestions much appreciated. 
Best wishes,
Nick.

**Comment by darribas** [comment]
It seems it's a typo as it should be `centroid`. Try that and report please. More generally, I'd strongly recommend to use the most up-to-date version of the course, which is available at:

> [http://darribas.org/gds17/](http://darribas.org/gds17/)

**Comment by nickbearman** [comment]
I hate typos! Thank you..... it worked fine.

I will have a look at the link. At first glace it seemed that gds_scipy16 was a shorter course, and there wasn't a gds_scipy17 I don't think. I will have a look at gds17.
