### ISSUE TITLE
05_spatial_clustering.ipynb uses wrong file link

### ISSUE THREAD

**Issue by ljwolf** [darribas/gds_scipy16#6]
Either the second or the third cell of `05_spatial_clustering` needs a minor edit. 

``` python
# Adjust this to point to the right file in your computer
abb_link = '../data/listings.csv.gz'
zc_link = '../data/Zipcodes.geojson'
```

``` python
lst = pd.read_csv(link)
```

I think that `link` in the third cell should be `abb_link`.

**Comment by darribas** [comment]
This seems to be fixed by @weikang9009 as part of PR #5.
